from localConstants import *

# Generated files names:
TAPS_INPUT = DATA_FOLDER + r"\\TAPS.csv"
USERS_INPUT = DATA_FOLDER + r"\\USERS.csv"
FINAL_DATASET = DATA_FOLDER + r"\\final.csv"
MIT_USERS_INPUT = DATA_FOLDER + r"\\MIT_USERS.csv"
MIT_GROUP1_TAPS_INPUT = DATA_FOLDER + r"\\MIT_GROUP1_TAPS.csv"
MIT_GROUP2_TAPS_INPUT = DATA_FOLDER + r"\\MIT_GROUP2_TAPS.csv"
MIT_FINAL_DATASET = DATA_FOLDER + r"\\MIT_final.csv"
MIT_GROUP1_NQI_FEATURES = DATA_FOLDER + r"\\MIT_GROUP1_NQI_FEATURES.csv"
MIT_GROUP2_NQI_FEATURES = DATA_FOLDER + r"\\MIT_GROUP2_NQI_FEATURES.csv"
KAGGLE_TAPS_INPUT = DATA_FOLDER + r"\\KAGGLE_TAPS.csv"
KAGGLE_USERS_INPUT = DATA_FOLDER + r"\\KAGGLE_USERS.csv"
KAGGLE_FINAL_DATASET = DATA_FOLDER + r"\\KAGGLE_final.csv"
# Others
TAPS_THRESHOLD = 2000 # changes to 500 for test data

