from localConstants import *

# Generated files names:
TAPS_INPUT = DATA_FOLDER + r"\\TAPS.csv"
USERS_INPUT = DATA_FOLDER + r"\\USERS.csv"
KAGGLE_DATA_ARTICLE_METHOD1_FEATURES = DATA_FOLDER + r"\\final.csv"
MIT_USERS_INPUT = DATA_FOLDER + r"\\MIT_USERS.csv"
MIT_TAPS_INPUT = DATA_FOLDER + r"\\MIT_TAPS.csv"
MIT_FINAL_DATASET = DATA_FOLDER + r"\\MIT_final.csv"
MIT_NQI_FEATURES = DATA_FOLDER + r"\\MIT_NQI_FEATURES.csv"
KAGGLE_TAPS_INPUT = DATA_FOLDER + r"\\KAGGLE_TAPS.csv"
KAGGLE_USERS_INPUT = DATA_FOLDER + r"\\KAGGLE_USERS.csv"
KAGGLE_FINAL_DATASET = DATA_FOLDER + r"\\KAGGLE_final.csv"
KAGGLE_NQI_FEATURES =  DATA_FOLDER + r"\\KAGGLE_NQI_FEATURES.csv"
# Others
TAPS_THRESHOLD = 2000 # changes to 500 for test data

